name: Brew Release

on:
  push:
    tags:
      - 'v*'

jobs:
  homebrew-releaser:
    runs-on: ubuntu-latest
    name: homebrew-releaser
    steps:
      - name: Release my project to my Homebrew tap
        uses: Justintime50/homebrew-releaser@v1
        with:
          homebrew_owner: {{cookiecutter.repo_owner}}
          homebrew_tap: {{cookiecutter.homebrew_repo_name}}
          formula_folder: Formula
          {% raw %}
          github_token: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          {% endraw %}
          commit_owner: github-actions[bot]
          commit_email: github-actions[bot]@users.noreply.github.com

          install: 'bin.install "src/{{cookiecutter.project_name}}.sh" => "{{cookiecutter.project_name}}"'
